In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import requests
from pprint import pprint
import json
from sqlalchemy import create_engine
from sqlalchemy.ext.automap import automap_base
#from pandas.io.json import json_normalize

In [2]:
url = "https://restcountries.eu/rest/v2/all"

In [3]:
response = requests.get(url)
data = response.json()
#df = pd.json_normalize(data)
#df.head()

In [4]:

#df = pd.DataFrame(data['alpha2Code']['currencies'][0]['name'])

dataframe = pd.DataFrame(data)
dataframe

,name,topLevelDomain,alpha2Code,alpha3Code,callingCodes,capital,altSpellings,region,subregion,population,...,timezones,borders,nativeName,numericCode,currencies,languages,translations,flag,regionalBlocs,cioc
0,Afghanistan,[.af],AF,AFG,[93],Kabul,"[AF, Afġānistān]",Asia,Southern Asia,27657145,...,[UTC+04:30],"[IRN, PAK, TKM, UZB, TJK, CHN]",افغانستان,004,"[{'code': 'AFN', 'name': 'Afghan afghani', 'sy...","[{'iso639_1': 'ps', 'iso639_2': 'pus', 'name':...","{'de': 'Afghanistan', 'es': 'Afganistán', 'fr'...",https://restcountries.eu/data/afg.svg,"[{'acronym': 'SAARC', 'name': 'South Asian Ass...",AFG
1,Åland Islands,[.ax],AX,ALA,[358],Mariehamn,"[AX, Aaland, Aland, Ahvenanmaa]",Europe,Northern Europe,28875,...,[UTC+02:00],[],Åland,248,"[{'code': 'EUR', 'name': 'Euro', 'symbol': '€'}]","[{'iso639_1': 'sv', 'iso639_2': 'swe', 'name':...","{'de': 'Åland', 'es': 'Alandia', 'fr': 'Åland'...",https://restcountries.eu/data/ala.svg,"[{'acronym': 'EU', 'name': 'European Union', '...",
2,Albania,[.al],AL,ALB,[355],Tirana,"[AL, Shqipëri, Shqipëria, Shqipnia]",Europe,Southern Europe,2886026,...,[UTC+01:00],"[MNE, GRC, MKD, KOS]",Shqipëria,008,"[{'code': 'ALL', 'name': 'Albanian lek', 'symb...","[{'iso639_1': 'sq', 'iso639_2': 'sqi', 'name':...","{'de': 'Albanien', 'es': 'Albania', 'fr': 'Alb...",https://restcountries.eu/data/alb.svg,"[{'acronym': 'CEFTA', 'name': 'Central Europea...",ALB
3,Algeria,[.dz],DZ,DZA,[213],Algiers,"[DZ, Dzayer, Algérie]",Africa,Northern Africa,40400000,...,[UTC+01:00],"[TUN, LBY, NER, ESH, MRT, MLI, MAR]",الجزائر,012,"[{'code': 'DZD', 'name': 'Algerian dinar', 'sy...","[{'iso639_1': 'ar', 'iso639_2': 'ara', 'name':...","{'de': 'Algerien', 'es': 'Argelia', 'fr': 'Alg...",https://restcountries.eu/data/dza.svg,"[{'acronym': 'AU', 'name': 'African Union', 'o...",ALG
4,American Samoa,[.as],AS,ASM,[1684],Pago Pago,"[AS, Amerika Sāmoa, Amelika Sāmoa, Sāmoa Amelika]",Oceania,Polynesia,57100,...,[UTC-11:00],[],American Samoa,016,"[{'code': 'USD', 'name': 'United State Dollar'...","[{'iso639_1': 'en', 'iso639_2': 'eng', 'name':...","{'de': 'Amerikanisch-Samoa', 'es': 'Samoa Amer...",https://restcountries.eu/data/asm.svg,[],ASA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,Wallis and Futuna,[.wf],WF,WLF,[681],Mata-Utu,"[WF, Territory of the Wallis and Futuna Island...",Oceania,Polynesia,11750,...,[UTC+12:00],[],Wallis et Futuna,876,"[{'code': 'XPF', 'name': 'CFP franc', 'symbol'...","[{'iso639_1': 'fr', 'iso639_2': 'fra', 'name':...","{'de': 'Wallis und Futuna', 'es': 'Wallis y Fu...",https://restcountries.eu/data/wlf.svg,[],
246,Western Sahara,[.eh],EH,ESH,[212],El Aaiún,"[EH, Taneẓroft Tutrimt]",Africa,Northern Africa,510713,...,[UTC+00:00],"[DZA, MRT, MAR]",الصحراء الغربية,732,"[{'code': 'MAD', 'name': 'Moroccan dirham', 's...","[{'iso639_1': 'es', 'iso639_2': 'spa', 'name':...","{'de': 'Westsahara', 'es': 'Sahara Occidental'...",https://restcountries.eu/data/esh.svg,"[{'acronym': 'AU', 'name': 'African Union', 'o...",
247,Yemen,[.ye],YE,YEM,[967],Sana'a,"[YE, Yemeni Republic, al-Jumhūriyyah al-Yamani...",Asia,Western Asia,27478000,...,[UTC+03:00],"[OMN, SAU]",اليَمَن,887,"[{'code': 'YER', 'name': 'Yemeni rial', 'symbo...","[{'iso639_1': 'ar', 'iso639_2': 'ara', 'name':...","{'de': 'Jemen', 'es': 'Yemen', 'fr': 'Yémen', ...",https://restcountries.eu/data/yem.svg,"[{'acronym': 'AL', 'name': 'Arab League', 'oth...",YEM
248,Zambia,[.zm],ZM,ZMB,[260],Lusaka,"[ZM, Republic of Zambia]",Africa,Eastern Africa,15933883,...,[UTC+02:00],"[AGO, BWA, COD, MWI, MOZ, NAM, TZA, ZWE]",Zambia,894,"[{'code': 'ZMW', 'name': 'Zambian kwacha', 'sy...","[{'iso639_1': 'en', 'iso639_2': 'eng', 'name':...","{'de': 'Sambia', 'es': 'Zambia', 'fr': 'Zambie...",https://restcountries.eu/data/zmb.svg,"[{'acronym': 'AU', 'name': 'African Union', 'o...",ZAM
249,Zimbabwe,[.zw],ZW,ZWE,[263],Harare,"[ZW, Republic of Zimbabwe]",Africa,Eastern Africa,14240168,...,[UTC+02:00],"[BWA, MOZ, ZAF, ZMB]",Zimbabwe,716,"[{'code': 'BWP', 'name': 'Botswana pula', 'sym...","[{'iso639_1': 'en', 'iso639_2': 'eng', 'name':...","{'de': 'Simbabwe', 'es': 'Zimbabue', 'fr': 'Zi...",https://restcountries.eu/data/zwe.svg,"[{'acronym': 'AU', 'name': 'African Union', 'o...",ZIM

In [15]:

transformed = dataframe[['name', 'alpha3Code', 'capital', 'region', 'subregion','population', 'flag','nativeName']].copy()
transformed.head()

,name,alpha3Code,capital,region,subregion,population,flag,nativeName
0,Afghanistan,AFG,Kabul,Asia,Southern Asia,27657145,https://restcountries.eu/data/afg.svg,افغانستان
1,Åland Islands,ALA,Mariehamn,Europe,Northern Europe,28875,https://restcountries.eu/data/ala.svg,Åland
2,Albania,ALB,Tirana,Europe,Southern Europe,2886026,https://restcountries.eu/data/alb.svg,Shqipëria
3,Algeria,DZA,Algiers,Africa,Northern Africa,40400000,https://restcountries.eu/data/dza.svg,الجزائر
4,American Samoa,ASM,Pago Pago,Oceania,Polynesia,57100,https://restcountries.eu/data/asm.svg,American Samoa

In [16]:
renamed = transformed.rename(columns={"name":"country", "alpha3Code":"country_code", "nativeName":"native_name"})
renamed.head()

,country,country_code,capital,region,subregion,population,flag,native_name
0,Afghanistan,AFG,Kabul,Asia,Southern Asia,27657145,https://restcountries.eu/data/afg.svg,افغانستان
1,Åland Islands,ALA,Mariehamn,Europe,Northern Europe,28875,https://restcountries.eu/data/ala.svg,Åland
2,Albania,ALB,Tirana,Europe,Southern Europe,2886026,https://restcountries.eu/data/alb.svg,Shqipëria
3,Algeria,DZA,Algiers,Africa,Northern Africa,40400000,https://restcountries.eu/data/dza.svg,الجزائر
4,American Samoa,ASM,Pago Pago,Oceania,Polynesia,57100,https://restcountries.eu/data/asm.svg,American Samoa

In [14]:
csv_file = "../ETL-Project/resources/gdp.csv"
gdp = pd.read_csv(csv_file)
gdp.head()

          COUNTRY  GDP (BILLIONS) CODE
0     Afghanistan           21.71  AFG
1         Albania           13.40  ALB
2         Algeria          227.80  DZA
3  American Samoa            0.75  ASM
4         Andorra            4.80  AND

In [24]:
gdp_new_df = gdp.rename(columns={"COUNTRY":"country", "GDP (BILLIONS)": "gdp", "CODE":"country_code"})
gdp_new_df.head()

          country     gdp country_code
0     Afghanistan   21.71          AFG
1         Albania   13.40          ALB
2         Algeria  227.80          DZA
3  American Samoa    0.75          ASM
4         Andorra    4.80          AND

In [25]:
gdp_new_df.to_sql(name='gdp', con=engine, if_exists='append', index=False)

In [26]:
connection_string = "postgres:postgres@localhost:5432/countries_db"
engine = create_engine(f'postgresql://{connection_string}')

In [27]:
engine.table_names()

['world_table', 'gdp']

['world_table']

In [19]:
renamed.to_sql(name='world_table', con=engine, if_exists='append', index=False)